---
- hosts: gluster
  vars_files:
    - vars.yml

  tasks:
    - name: Create mount point for gluster
      become: yes
      file:
        path: /data/brick1
        state: directory

    - name: ...
      become: yes
      shell: "yum install python2-dnf -y"

    - name: Install the glusterfs server
      become: yes
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - glusterfs-server
...

