---
- hosts: gluster

  tasks:
    - name: Create mount point for gluster
      become: yes
      file:
        path: /data/brick
        state: directory

    - name: Install the glusterfs server
      become: yes
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - glusterfs-server

    - name: Start glusterfs service
      become: yes
      service:
        name: glusterd
        state: started

    - name: Ensure firewall for each instance is opened
      become: yes
      firewalld:
        zone: trusted
        state: enabled
        source: "{{ item }}"
      with_items: "{{ cluster_ips }}"

    - name: Create gluster volume
      become: yes
      gluster_volume:
        name: test_vol
        state: present
        bricks: /data/brick
        cluster: "{{ cluster_ips }}"
      run_once: true
...

